services:
  backend:
    build: ./Rachel-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Rachel-backend/.env
    volumes:
      - ./Rachel-backend/data:/app/data

  frontend:
    build: ./Rachel-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
