services:
  backend:
    build: ./Rachel-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Rachel-backend/.env
    volumes:
      - ./Rachel-backend/data:/app/data

  frontend:
    build:
      context: ./Rachel-frontend
      args:
        - VITE_API_URL=https://rachel-lh60.onrender.com
    ports:
      - "80:80"
    depends_on:
      - backend
